[package]
name = "NeroShizaDev-OS"
version = "0.3.0"
authors = ["NeroShizaDev"]
edition = "2024"

[lib]
name = "blog_os"
path = "core/lib.rs"

[[bin]]
name = "blog_os"
path = "core/main.rs"

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false

[dependencies]
bootloader_api = "0.11.15"
lazy_static = { version = "1.5", features = ["spin_no_std"] }
pc-keyboard = "0.8.0"
pic8259 = "0.11.0"
spin = "0.10.0"
uart_16550 = "0.6.0"
x86_64 = "0.15.4"

[build-dependencies]
bootloader = "0.11.15"

[package.metadata.bootimage]
run-args = ["-cpu", "max"]
test-args = [
    "-cpu", "max",
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio",
    "-display", "none",
]
test-success-exit-code = 33
